README.md

Zipping a directory with the old example would change the content of a file by adding a newline to the data getting zipped.
This is bad if you want to validate files of zip with checksums or, in my case, it corrupts git index files if you zip a git-directory.

Readme: Print data instead of puts

---

lib/zip/file.rb

In one of our tests, we noticed that we were getting intermittent `Errno::ENOENT: No such file or directory` errors here when reaching `::File.rename(tmp_filename, self.name)`. 
After some investigation I found that the garbage collector happened to be running the finalizer for `tmpfile` during the entry writing block in `File#commit`, which tries to unlink the file (and succeeds if you're on a non-Windows environment).

prevent tempfile path from being unlinked by garbage collection

---

lib/zip/file.rb
lib/zip/output_stream.rb

This is a fix for #119.
The test suite still runs, but I have not added a test for this fix because I'm not sure if the behavior I defined is correct.
1. **Force binary mode** (`file.rb`): I noticed that the errors went away when I opened files in binary mode, like `rubyzip` itself does when you pass a filename to `Zip::File.open`, so now it forces binary mode when you pass an IO object.
1. **Abort unnecessary writes** (`output_stream.rb`): If you don't pass a stream which was opened for writing, then this results in a "not opened for writing" error, even if you didn't actually try to write anything.
The second part is probably not correct; I imagine the best fix would be one that only bothers doing `zf.write_buffer(io)` if changes were actually made to the in-memory archive.

Be smarter about handling buffer file modes

---

.gitignore
lib/zip/entry.rb
lib/zip/entry_set.rb
test/entry_set_test.rb

So here's another take on https://github.com/rubyzip/rubyzip/pull/217
In the end I decided that once case-insensitivity is being implemented in this single method, adding an extra configuration option would not be justified, as that option would not turn `rubyzip` case-insensitive throughout.
Pull if you consider this solution acceptable.

Case insensitivity option for #find_entry

---

lib/zip.rb
lib/zip/entry_set.rb
test/case_sensitivity_test.rb
test/entry_set_test.rb

Case insensitivity is required by certain other software packages (most notably, MS EXCEL, may God punish its developers) that do not pay attention to filename capitalization.
@rastarobot attempted to mitigate that in Issue #222, but did it rather sloppily, so let's do it right this time.
Now `::Zip` has a `case_insensitive_match` parameter, which, if set to `true`, makes `File.TXT` and `file.txt` equivalent for all intents and purposes.

Less sloppy implementation of case insensitive matching

---

README.md
lib/zip/file.rb
test/file_permissions_test.rb

This fixes #204.
Instead of inheriting the permissions from the tmp directory, new files should
have permissions that reflect the defaults on the system taking umask into
account.
It seems that (unix) permissions of 666 - umask are as close to a standard as
anything [1] and that 'touch' uses this. On Windows it seems sensible to just
use 644 directly [2].
[1] http://unix.stackexchange.com/a/102080
[2] http://ruby-doc.org/core-1.9.3/File.html

Do something more expected with new file permissions.

---

lib/zip/file.rb
test/file_test.rb

It'd be really handy if `open_buffer` accepted a StringIO parameter, because I could just give it the `body` attribute of a Rails request, which can either be an IO or a StringIO.
The `open_buffer` implementation wraps String buffers into StringIO instances, so it appears that it should be able to use a StringIO without any deep changes. I updated the checks and added a test verifying the new code.
Will you please consider merging this?
Thank you very much for rubyzip!

Accept StringIO in Zip.open_buffer

---

lib/zip/entry.rb
lib/zip/file.rb
lib/zip/input_stream.rb
test/case_sensitivity_test.rb
test/input_stream_test.rb

Hey gang. This was necessary so I could stream a zipfile from S3 using the s3io gem. It seems a little bonkers to keep hard-coding the names of IO-like classes into rubyzip, doesn't it?
Additionally I had to splice in `seek` and `tell` methods to s3io using the more Rubyish ``@pos``, which it supports instead. Maybe rubyzip could be made to use those methods as well, for increased compatibility?

Use duck typing with IO methods.

---

lib/zip/deflater.rb
lib/zip/output_stream.rb

When support for ZipCrypto was added, an internal StringIO buffer was added to Deflater, in order to fix a decryption bug. While this worked, it caused unlimited memory growth when compressing large files.
The proper fix is to writer the encryption header in init_next_entry instead of finalize_current_entry, so the headers are written before any encrypted data. Because of this fix we can remove the buffering in
Deflater, which keeps memory usage low and allows to stream compressed data while it is written.
This should fix issue #233.

Fix high memory usage due to Deflater buffering

---

lib/zip/entry.rb
test/settings_test.rb

While I added this attibute in https://github.com/rubyzip/rubyzip/pull/195 I have no idea how to check `STDERR` output.
Now I found out, that there is `assert_output` method in `minitest`, so test will check it.

Add correct test for `Zip.warn_invalid_date` attribute

---

lib/zip.rb
lib/zip/file.rb

- #185 reported that a file was unexpectedly deleted by the `Tempfile` finalizer and added `ObjectSpace.undefine_finalizer` to work around that.
- #252 reported that `ObjectSpace` introduced in #185 should be avoided for JRuby.
- 8447f0e2302989615eb0141f31911fe36130f292 removed `ObjectSpace` but reintroduced the problem of #185.
This patch fixes both #185 and #252.  It removes use of `Tempfile` so we don't fight its finalizer and don't need to use `ObjectSpace`.  It uses `Dir::Tmpname` and `File` to make the named temporary file instead.  There is no chance of accidental unlink and the code becomes more clear.

Fix accidental unlink (#185) without using ObjectSpace (#252)

---

samples/example_recursive.rb

Replacing 'puts' with 'write' as 'puts' was adding extra lines in files,
damaging them. Ref : https://github.com/rubyzip/rubyzip/issues/260

Fix in example_recursive

---

Changelog.md

RubyZip 1.2.0 was released without updating `Changelog.md`.  This patch copies the notes from the [GitHub releases page](https://github.com/rubyzip/rubyzip/releases/tag/v1.2.0) into the changelog.

Add changelog entries for RubyZip 1.2.0

---

test/file_test.rb
test/gentestfiles.rb

After running the tests there was a file left in the project directory,
'empty.zip', which was simply 'touch'ed to use as a null file. Switch to create
this as one of the generated test files so it's cleaned up automatically.
Also, use 'null.zip' as the name as there is already an 'empty.zip' generated
that is a zip file, but empty.

Clean up empty.zip after running tests.

---

lib/zip/file.rb
test/file_permissions_test.rb
test/file_test.rb

This is an attempt to fix #294 in a more sensible way than was attempted, by me :-), previously.
I used the improved tests by @metavida.
To fix it I stopped the original temporary files from being created with 0600 permissions. Is this sensible? Have I missed something?

Fix permissions on new zip files (#294)

---

test/file_test.rb

This reverts commit 6597af12573180b5b8c1c87fffe178895ddbecfd since
7caab1f already fixed the same thing. It should fix the build.

Revert "Cleanup after ourselves"

---

lib/zip/entry.rb

This is a change to support cp932, AKA Windows-31J or Shift_JIS, encoding that is used in Japanese Windows.
There may be Kanji characters that have \x5c byte in their codepoint.
tr consume the byte and make the codepoint invalid.
Here's an example.
```
irb(main):002:0> '表'.encode('windows-31j').bytes.map { |x| x.to_s(16) }
=> ["95", "5c"]                                                                                                          
```

remove tr to support cp932 encoding

---

README.md

The instructions for zipping a directory recursively uses `puts`:
```
def put_into_archive(disk_file_path, io, zip_file_path)
io.get_output_stream(zip_file_path) do |f|
f.puts(File.open(disk_file_path, 'rb').read)
end
end
```
This appends a newline character `0x0A` at the end of each file, which has just caused me a number of headaches :)

Replace puts with write in README.md for dir recursion

---

.simplecov
lib/zip/ioextras/abstract_output_stream.rb
test/central_directory_entry_test.rb
test/crypto/null_encryption_test.rb
test/entry_set_test.rb
test/entry_test.rb
test/filesystem/file_nonmutating_test.rb
test/filesystem/file_stat_test.rb
test/input_stream_test.rb
test/ioextras/abstract_input_stream_test.rb
test/ioextras/fake_io_test.rb
test/local_entry_test.rb
test/test_helper.rb

Fix following deprecated warnings in `rake test`.
- `Use assert_nil if expecting nil`
- `::[] is deprecated. Use ::new instead.`
- `constant ::Fixnum is deprecated` in Ruby 2.4 https://bugs.ruby-lang.org/issues/12005
Thanks.

Fix deprecated warnings

---

lib/zip/file.rb
test/file_test.rb

File::open_buffer should function like open in that a block is optional.  This PR makes open_buffer behave similar to File::open by returning the zf if no block given.

allows open_buffer to work without a given block

---

README.md
samples/example_recursive.rb

I would like to make naming more consistent and understandable especially on README so that new developers can easily get familiar with rubyzip.
IMHO, I would like to rename variables on README in the following way.
* io => zipfile
* First example uses `zipfile` and it is an object of Zip::File
* Since Zip::File uses IO-like objects in some cases, this change could reduce some confusion.
* os => f
* Second example uses `f` and it is an object of Tempfile
Any better ideas are welcome.

Make naming on README more consistent

---

lib/zip/streamable_stream.rb

I would like to save temporary files to a temporary directory.
Because the primary objective of `@temp_file` in `Zip::StreamableStream` is to temporarily hold data of an entry as a file, the upper directory does not need to be the current directory.
This patch set the directory to default `Dir.tmpdir`. As a result, we can stop temporary files from filling up current directory.
c.f. http://ruby-doc.org/stdlib-2.4.1/libdoc/tempfile/rdoc/Tempfile.html

Save temporary files to a temporary directory

---

README.md

This fixes formatting in the Markdown in the README.

README: Use a blockquote to make text readable

---

.travis.yml

Rubinius with Bundler 1.16.0 has a problem to do with Rubinius' autoloading behavior.
One Bundler file ('bundler/deprecate') is needed way early, and to make that work on Rubinius, I have opted to use Ruby's `RUBYOPT` environment variable to add a require on the `ruby` command level.
- see bundler/bundler#6163
**Update:** This makes `bundle install` pass, but `bundle exec rake` still raises a NameError about Bundler::Deprecate.

 Travis: Workaround a rbx-3 autoload issue  WIP

---

lib/zip/input_stream.rb

`Zip::Entry.empty?` doesn't exist, but Rubocop suggested it as a fix instead of `size == 0`.  This particular instance only fails under very certain circumstances.  I have a file that causes it to fail but it's an proprietary internal file that's automatically generated by one of our vendors so I'm unable to share it.
I only fixed this one specific instance, there may be other regressions caused by the Rubocop cleanup so perhaps the entire commit should be double-checked.

Fix regression caused by automatic Rubocop fixes

---

lib/zip/file.rb
test/file_test.rb

Right now if you call `Zip::File#close` on a zipfile that's been opened with a `StringIO` you get an exception in `on_success_replace`.  This fixes this since calling `.close` here should be a no-op anyway as there's no on-disk file to replace.

Added fix for calling 'close' on a StringIO-backed zip file, and specs

---

lib/zip/filesystem.rb
test/filesystem/directory_test.rb

This is an attempt to fix #356 by passing through the glob to the underlying implementation. This takes into account the current working directory within the zip archive.

Fix Zip::FileSystem::ZipFsDir#glob

---

Changelog.md

1.2.2 was already released in #376, so unfortunately this is too late for inclusion in that, but at least future releases will have it.
This is just a list of the titles of all non-merge commits since 1.2.1, so it won't be as concise or readable a summary as for previous releases, but it's better than nothing, and anyone is welcome to volunteer to condense it further.
Closes #378.

Add Changelog for 1.2.2 (#378)

---

lib/zip/entry.rb

Lib::Zip::Entry uses Pathname; if the project that is using RubyZip doesn't already require 'pathname', a bizarre error message of the following form will be generated:
/Users/homedir/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rubyzip-1.2.2/lib/zip/entry.rb:116:in `name_safe?': uninitialized constant Zip::Entry::Pathname (NameError)
As Pathname is used internally, I believe it should be imported from within RubyZip. If there is a better solution to this issue, I'd love to know!

require pathname where it is used

---

.travis.yml
lib/zip/entry.rb
lib/zip/extra_field.rb
lib/zip/inflater.rb

Hi,
I got FrozenError when I used rubyzip gem with `--enable-frozen-string-literal` option.
```
FrozenError:
can't modify frozen String, created at C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubyzip-1.2.2/lib/zip/entry.rb:605
```
This PR is to fix the above error.

fixed FrozenError caused by frozen-string-literal

---

lib/zip/entry.rb

I found some strange commas and removed them.

remove some strange commas

---

.travis.yml

Many recent PRs had spurious CI failures due to end of life ruby versions in CI.
1. The (recent) failures were on [`gem update --system`](https://travis-ci.org/rubyzip/rubyzip/jobs/501116591) for old versions of ruby that are end-of-life.
Ruby versions < 2.3 are now end of life: https://www.ruby-lang.org/en/downloads/branches and 2.3 is itself scheduled to be EOL on 31 Mar 2019.
2. #390 added workarounds to not run `gem update --system` on those old versions. However, looking at git blame, it looks like `gem update --system` was added a long time ago in 2bd6ebea11b64f47158c3553992943b17a8566f0. In #346, 43f01f4631503912b08b6578a64bc406030d9bce mentions that it shouldn't be needed and removes it but then brings it back in cbdea2a3311bdd8c776afa183c1b2d82ad77ddbb (without comment, even …

Update supported ruby versions

---

.travis.yml

This PR updates the CI matrix to latest versions of Ruby.
Also: 
- drop unused Travis configuration: sudo: false - see https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration for historical detail about when it was removed.

CI: update to latest MRI, drop a setting

---

Changelog.md
lib/zip/version.rb

@olleolleolle @aspiers @vipulnsward @bdewater @hainesr @d235j @taichi-ishitani @mihyaeru21 @tuzovakaoff @JackMc Thanks for your recent contributions to rubyzip 👏.
I'm helping @simonoff with maintenance on this library now.
I'm working toward this release mainly to fix any problems I caused with #376 in trying to fix CVE-2018-1000544 (https://github.com/rubyzip/rubyzip/issues/369). I've also reviewed and pulled in some other recent small fix PRs and done some housekeeping for CI, but I haven't attempted to merge anything larger or further down in the backlog for this release.
1. Do you have any views on https://github.com/rubyzip/rubyzip/pull/391 ? That's the last piece needed for this release, and it has some security implications. It would be good to have someone other than me review it. …

Bump version to 1.2.3

---

.travis.yml
Changelog.md

- Xenial recently became the default `dist` on Travis, which broke the Java builds. Trusty has now reached [end of Standard Support](https://wiki.ubuntu.com/Releases) but not yet end of life.
- For more info on Java changes in Xenial: https://travis-ci.community/t/the-travis-ci-build-could-not-be-completed-due-to-an-error/1345
- Also omit the ruby patch versions so we don't have to keep updating them.
- The rubinius maintainer asked us to move from rbx-3 to rbx-4 in https://github.com/rubinius/rubinius/issues/3811, which is an easy change (on Trusty; on Xenial it [doesn't appear to exist](https://travis-ci.org/rubyzip/rubyzip/jobs/555358450)).
- We had another apparently spurious drop in coverage in coveralls, but it still seems less flaky than it was before …

Fix CI and try rbx-4

---

lib/zip/file.rb
test/file_test.rb

Things are now more carefully set up, and if a buffer is passed in which represents a file that already exists then this is taken into account. All initialization is now done in File.new, rather than being split between there and File.open_buffer.
This has also needed a bit of a re-write of Zip::File.initialize. I've tried to bring some logic to it as a result, and have added comments to explain what is now happening.
This PR includes some other related fixes too. All tests pass.

Fix #280 - `open_buffer` mangles the content of the buffer it is given.

---

rubyzip.gemspec

Add [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. This'll allow people to more easily access the source code, raise issues and read the changelog. These `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `wiki_uri` and `source_code_uri` links will appear on the rubygems page at https://rubygems.org/gems/rubyzip and be available via the rubygems API after the next release.

Add project metadata to the gemspec

---

lib/zip/file.rb
test/file_test.rb

Adding uncompressed files to a zip archive can be overly complex, so this convenience method makes it easier. Examples of the confusion caused by the current situation are in #286 and https://github.com/sul-dlss/preservation_catalog/issues/737.

Zip::File.add_stored() to add uncompressed files.

---

Changelog.md
README.md
lib/zip.rb
lib/zip/entry.rb
lib/zip/errors.rb
test/file_extract_test.rb

Fix https://github.com/rubyzip/rubyzip/issues/193 ("Protection Against Zip Bombs")
Currently there is no way to safely check how much data the `Zip::Entry#extract` method will actually extract, because the uncompressed size reported in the zip can be spoofed, and the extraction happens in the method where the caller can't check on its progress.
This can lead to denial of service through disk exhaustion if the input is a [zip bomb](https://en.wikipedia.org/wiki/Zip_bomb).
The approach taken here is based on the `validateEntrySizes` option for node's [yauzl](https://www.npmjs.com/package/yauzl) unzipping library: rubyzip can check that it doesn't extract (much) more than the expected amount of data, based on the uncompressed size reported in the zip file. That way the caller can check the …

Validate entry sizes when extracting

---

rubyzip.gemspec

Remove the `test_files` from the gemspec, because rubyzip's test files are quite large now and include some malicious zip files that trigger virus scanners on machines that have the gem installed.
Fix https://github.com/rubyzip/rubyzip/issues/384 .
The trend in https://github.com/rubygems/rubygems/issues/735 seems to be to remove `test_files` files from the gemspec. There is some good discussion in that ticket about why this may not be the best thing to do long term (pending changes in rubygems to better support test files), but it does seem to be the preferred approach at the moment.
I am planning to add this to the upcoming 2.0 release. I will leave this open for approximately one week for comment.
CC @MaximeDerche @GElkayam

Remove test files from gem

---

.travis.yml
README.md
rubyzip.gemspec

Upgrade minimum supported ruby versions to include only supported rubies. This is planned as part of an upcoming major release (2.0).
This will hopefully make CI less fragile, allow us to upgrade our linting system, and allow us to take advantage of newer ruby features.
Fixes https://github.com/rubyzip/rubyzip/issues/404 .
- Ruby 2.3 has been EOL since the [end of March 2019](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/).
- Support for JRuby 9.1 ended [at the end of 2017](https://github.com/jruby/jruby/wiki/Roadmap).
- JDK7 is still in [extended support](https://en.wikipedia.org/wiki/Java_version_history), but it seems that JRuby has [dropped it from CI](https://github.com/jruby/jruby/blob/37e63e4d57354daa419af9abc26a9b14b8010001/.travis.yml#L29-L30), and it …

Bump supported ruby versions

---

Changelog.md
README.md
lib/zip.rb
lib/zip/version.rb

Bump version to 2.0.0

---

lib/zip/entry.rb
lib/zip/extra_field/generic.rb
lib/zip/input_stream.rb
test/file_extract_test.rb
test/path_traversal_test.rb
test/settings_test.rb

This has the advantage of consistency and being able to turn them off with, e.g. `-W0`.
Also, make the messages themselves more consistent and check that they are actually output.
(@jdleesmiller I mentioned a while back in another PR that I would work this one up.)

Print library warnings to stderr with `warn` (not `puts`).

---

lib/zip/file.rb

I realized when working up #413 to fix #395 that this was missing, and would be much nicer to have than using `Zip::File.new` for most uses.

Add `options` parameter to `Zip::File.open`.

---

lib/zip/dos_time.rb
lib/zip/entry.rb
lib/zip/file.rb
test/file_options_test.rb

This PR was prompted by #395. When investigating that issue it quickly became obvious that there were deeper problems - as can be seen in the notes for that ticket.
This PR:
* Correctly applies the options specified in ::Zip::File.new, and supplies defaults for any not given.
* Fixes the `restore_times` option by actually storing the original timestamp of a file, and then optionally restoring it on extraction. It also adds tests for this functionality.
* Adds tests for the `restore_permissions` option.
* Does *not* add tests for the `restore_ownership` option. This needs some thinking about because restoring ownership would require other users to be set up on the test machine, and would also potentially require such tests to be run as root.
They are fairly simple fixes, once one has one's …

Fix `restore_times` option when extracting, and test file options

---

.travis.yml

This PR does three things:
* use a later Ubuntu distribution in the tests (Xenial);
* which allows us to specify the next LTS version of OpenJDK (11);
* and, turn on `fast_finish` so that builds are marked as complete as soon as possible.
It still tests with OpenJDK 8 as it's still in support.

Travis updates and tweaks

---

lib/zip/entry.rb
lib/zip/file.rb
test/file_options_test.rb
test/file_test.rb

See #422 for a detailed explanation of what is going on here.
This is the quick fix to ensure things are consistent for now. I will work up a PR with a longer term fix once we've decided what to do about it.

Sync options and fix inconsistent behaviour of `Zip::File#get_entry` and `Zip::File#find_entry`.

---

lib/zip/extra_field/universal_time.rb
test/extra_field_ut_test.rb

When working on #413 to fix #395 I discovered that there were a few problems with how the timestamps were being stored - particularly with the UniversalTime extra field. On even closer inspection, and after having consulted the UniversalTime specification (ftp://ftp.info-zip.org/pub/infozip/doc/), I found further issues.
This PR fixes those issues and makes the `UniversalTime` class more user-friendly. It also adds tests.
At a later date I will fold this in so that it is used to store and restore the timestamps of files, but I've left this for now as it has the side-effect of adding data (that might be unexpected/unwanted) between the filename and file data. In short, I wonder if we should allow some control over which extra fields are used, rather than inserting them by default, c.f. …

Fixes for the UniversalTime extra field

---

.travis.yml
lib/zip/crypto/decrypted_io.rb
lib/zip/entry.rb
lib/zip/extra_field.rb
lib/zip/file.rb
lib/zip/inflater.rb

Hi,
I got `FrozenError` when I use rubyzip gem --enable-frozen-string-literal option.
```
FrozenError:
can't modify frozen String: ""
```
This PR is to fix the above error.

Fix frozen error caused by frozen string literal

---

bin/console

I find myself testing things in `irb` enough that this has proved useful, so I decided to commit it.
It's purely a developer nicety so isn't stored in the gem.

Quickly fire up a console with 'zip' pre-loaded.

---

lib/zip/file.rb
lib/zip/output_stream.rb
test/output_stream_test.rb

Set OutputStream.write_buffer's default buffer to binmode

---

test/file_extract_test.rb

Using the current pack directives makes test_extract_incorrect_size fail
in s390x architecture because of the endian probably. This is the output
of the command executed by the test in amd64:
irb(main):001:0> [501, 500000, 1].pack('LLS')
=> "\xF5\x01\x00\x00 \xA1\a\x00\x01\x00"
And the output of the same command in s390x:
irb(main):001:0> [501, 500000, 1].pack('LLS')
=> "\x00\x00\x01\xF5\x00\a\xA1 \x00\x01"
Changing to 'V' pack directive like is used in
lib/zib/central_directory.rb fixes the test in s390x and does not add a
regression in amd64.
FTR I've faced this issue in ruby-zip Debian package in Ubuntu, here is the log: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-focal/focal/s390x/r/ruby-zip/20200323_152440_d8d79@/log.gz

test/file_extract_test.rb: fix test_extract_incorrect_size in s390x arch

---

rubyzip.gemspec

The valid SPDX license is "BSD-2-Clause" instead of "BSD 2-Clause".
ref. https://spdx.org/licenses/

Use correct SPDX license identifier

---

Changelog.md
lib/zip/ioextras/abstract_input_stream.rb
test/input_stream_test.rb

This PR fixes #461.
If an input stream has been read from, and left some data in the internal buffer, then a subsequent `read`, with no amount of bytes to be read having been specified, will raise an error when comparing to `nil`. This fix checks that the number of bytes specified in the `read` is not `nil` before comparing with the size of the internal buffer.

Fix input stream partial read error.

---

lib/zip/deflater.rb
test/encryption_test.rb

With jruby there was problem when creating large zipped files. I found that deflate did not flush zlib stream like it did with cruby.

Fix zlib deflate buffer growth

---

test/central_directory_test.rb
test/test_helper.rb

This change has several benefits:
* When errors occur, the test provides useful feedback, showing you
expected vs. actual.
* We no longer need to open and modify the Enumerable module.
* The test is more readable.

Remove compare_enumerables from test_helper.rb

---

test/basic_zip_file_test.rb

We can get the same strength of assertions with less code. Also, by
using assert_equal instead of assert, we get better feedback when
assertion does not meet expectations.

Simplify assertions in basic_zip_file_test

---

lib/zip/dos_time.rb
lib/zip/entry.rb
test/output_stream_test.rb

Having a specific 'does this instance equal another instance' method is kind of annoying and breaks a number of things. Most obviously it breaks comparing to `nil`: `nil.dos_equals(other)` will fail where `nil == other` does not.
So this commit overrides `<=>` in `Zip::DOSTime` and deprecates `dos_equals`.
It should fix #216 in the process...

Replace and deprecate `Zip::DOSTime#dos_equals`.

---

lib/zip/entry.rb

Hi, I've been testing rubyzip with a Ruby fuzzing tool ([kisaten](https://github.com/zelivans/kisaten)) and found a few bugs. I wrote fixes for all the bugs and sending PRs now.
In this bug it appears that `ExtraField` can leave some members empty (nil), specifically `mtime` for `UniversalTime` and `NTFS`. I don't know if this is expected behavior but I created a specific fix for this issue by checking nil value in the `#time` function, otherwise it raises a `NoMethodError` and crashes the execution.
```
/home/ariel/afl-kisaten/private/sandbox/rubyzip/rubyzip/lib/zip/entry.rb:490:in `==': undefined method `dos_equals' for nil:NilClass (NoMethodError)
from /home/ariel/afl-kisaten/private/sandbox/rubyzip/rubyzip/lib/zip/entry_set.rb:53:in `=='
from …
```

Prevent NoMethodError crash with malformed zip in #time

---

.rubocop_todo.yml
lib/zip/entry.rb

But only do it after we have set filename encoding appropriately to
avoid breaking multibyte characters with `\`s in them.
Fixes #324.

Reinstate normalising pathname separators to `/`.

---

Changelog.md
lib/zip.rb
lib/zip/entry.rb
lib/zip/file.rb
test/file_options_test.rb

This PR is, finally, to finish off the work to fix and make consistent the options to restore file timestamps and file permissions on extraction.
The default options are now specified at the top level so that both `File` and `Entry` get a consistent view of them. They can still be overridden per-`File` - and per-`Entry` if needs be.
Additionally this PR enables timestamps to be restored on Windows.
This PR closes #422 and fixes #336.

Fix restore options consistency.

---

lib/zip/ioextras/abstract_output_stream.rb
test/ioextras/abstract_output_stream_test.rb

Hello rubyzip community! 👋 
I was thinking about making a small contribution in another area, so I went to run the test suite and noticed this deprecation warning: `abstract_output_stream_test.rb:60: warning: '$,' is deprecated`.
I learned that setting `$,` (aka `$OUTPUT_FIELD_SEPERATOR`) to a non-nil value is now deprecated. This was discussed in https://bugs.ruby-lang.org/issues/14240 and implemented in ruby/ruby@6298ec2.
As a result, I've modified both some test code and application code to assume a world in which this value is always `nil`. 
Since I'm new to this community, and this code [was originally almost 20 years ago(!)](https://github.com/rubyzip/rubyzip/commit/441dcb964393fcb43a4a507f8ff6402cf93ed8fb#diff-859f6edc8864e2e7b8ed6fad65231c59c3f648cc645f1d2ee81f73ca58f49d6fR401), …

Fix depreciation warning: abstract_output_stream_test.rb:60: warning: `$,' is deprecated

---

Changelog.md

Line 15 is same as line 18.
Line 15 (at 25795c7b 2021-05-18) is newer than line 18 (at 0a6037b0 2020-11-08), so this pull-request removes line 15.

Remove duplicated line on Changelog.md

---

.rubocop_todo.yml
Changelog.md
README.md
lib/zip/entry.rb
lib/zip/file.rb
lib/zip/file_split.rb
lib/zip/filesystem.rb
lib/zip/filesystem/zip_file_name_mapper.rb
lib/zip/input_stream.rb
lib/zip/output_stream.rb
samples/example_filesystem.rb
samples/example_recursive.rb
test/case_sensitivity_test.rb
test/encryption_test.rb
test/entry_test.rb
test/file_extract_test.rb
test/file_options_test.rb
test/file_permissions_test.rb
test/file_split_test.rb
test/file_test.rb
test/local_entry_test.rb
test/output_stream_test.rb
test/stored_support_test.rb
test/unicode_file_names_and_comments_test.rb
test/zip64_full_test.rb

This makes sense as named parameters make many things more usable.
It is a breaking change, so now is the right time as we're releasing 3.0 next.

Move to use named parameters for some classes (Entry already done)

---

.rubocop_todo.yml
lib/zip/central_directory.rb
lib/zip/entry.rb
lib/zip/extra_field.rb
lib/zip/extra_field/unknown.rb
test/extra_field_test.rb
test/extra_field_unknown_test.rb
test/local_entry_test.rb

When loading extra fields from both the central directory and local headers,
unknown fields were not merged correctly. They were being appended, which
means that we end up with the two versions stuck together - in some
cases duplicating the field completely.
This broke all kinds of things (like calculating the size of a local
header) in subtle ways.
This commit fixes this by implementing a new `Unknown` extra field type,
and making sure that when reading local and central extra fields they
are stored and preserved correctly. We cannot assume the unknown fields
use the same data in the local and central headers.
Fixes #505.

Fix reading unknown extra fields.

---

.github/workflows/tests.yml

This PR is to add Ruby 3.1 to CI.

add Ruby 3.1 to CI

---

lib/zip/entry.rb
lib/zip/output_stream.rb
test/entry_test.rb
test/file_test.rb

When passing an `Entry` type to `File#get_output_stream` the entry is
used to create a `StreamableStream`, which preserves all the info in the
entry, such as timestamp, etc. But then in `put_next_entry` all that is
lost due to the test for `kind_of?(Entry)` which a `StreamableStream` is
not. See #503 for details.
This change tests for `StreamableStream`s in `put_next_entry` and uses
them directly. Some set-up within `Entry` needed to be made more robust
to cope with this, but otherwise it's a low impact change, which does
fix the problem.
The reason this case was being missed before is that the tests weren't
testing `get_output_stream` with an `Entry` object, so I have also added
that test too.
Fixes #503.

Fix `OutputStream#put_next_entry` to preserve `StreamableStream`s.

---

README.md

The indentation of the sample code in the README was incorrect, so I fixed it.

Fix indentation in sample code

---

lib/zip/input_stream.rb
test/input_stream_test.rb

Currently, we raise an error for encrypted zip entries if `@decrypter` is a `NullEncryper`. However, the default value for `@decrypter` is actually `NullDecrypter`.

Fix unraised error on encrypted archives

---

lib/zip/entry.rb
lib/zip/file.rb
test/file_extract_directory_test.rb
test/file_extract_test.rb
test/file_options_test.rb
test/path_traversal_test.rb

This commit adds a parameter to the `File#extract` and `Entry#extract` methods so that a base destination directory can be specified for extracting archives in bulk to somewhere in the filesystem that isn't the current working directory. This directory is `.` by default. It is combined with the entry path - which shouldn't but could have relative directories (e.g. `..`) in it - and tested for safety before extracting.
Resolves #540.

Ensure that entries can be extracted safely without path traversal.

---

.github/workflows/tests.yml
README.md

The setup-ruby action installs an MSYS2 version of zip, so the step running `choco install zip` isn't needed.

Add two Windows head builds to CI, update README.md CI info

---

README.md

The readme threw me off the trail of needing to set `Zip.write_zip64_support` to true. Hoping a tweak to the readme will prevent others from making the same mistake.

Readme: Note write_zip64_support default is false before 3.0

---

lib/zip/file.rb
test/file_test.rb

Ref: https://github.com/rubyzip/rubyzip/commit/ef89a62b70d0b0c43a9579d414d5a917fef0cdc3
This fixes a regression in 2.4.rc1.
cc @hainesr

Fix `File#write_buffer` to always return the given `io`

---

lib/zip/entry.rb

Ran our app with warnings on, and found this one was coming from RubyZip itself.

Fix deprecation in Entry#get_input_stream

---

lib/zip/extra_field/ntfs.rb

Ref: https://bugs.ruby-lang.org/issues/20205
This patch will suppress the "literal string will be frozen in the future" warning on the 2.4 branch.
Steps to reproduce
---
Run the following commands with ruby 3.4.0preview1:
```console
$ cd /tmp
$ git clone git@github.com:rubyzip/rubyzip.git
$ cd rubyzip
$ git switch 2.4
$ bundle install
$ ruby -I lib -W:deprecated -e '
require "zip"
Zip::File.open("test/data/ntfs.zip") do |zip_file|
zip_file.each do |entry|
puts entry.get_input_stream.read
end
end
'
```
Expected result
---
```console
ntfs test
```
Actual result
---
```console
/private/tmp/rubyzip/lib/zip/extra_field/ntfs.rb:54: warning: literal string will be frozen in the future
ntfs test
```
Environment
---
```console
$ ruby -v
ruby 3.4.0preview1 (2024-05-16 master 9d69619623) …
```

Suppress "literal string will be frozen in the future" warning

---

rubyzip.gemspec

As a pupular gem, `rubyzip` implicitly requires that all privileged operations by any of the owners require OTP.
By explicitly setting `rubygems_mfa_required` metadata, the gem will show "NEW VERSIONS REQUIRE MFA" and "VERSION PUBLISHED WITH MFA" in the sidebar at https://rubygems.org/gems/rubyzip
NOTE: The explicit opt-in was introduced in the `master` branch via 1c06454, but has not been backported to `2.4`
Ref:
- https://blog.rubygems.org/2022/08/15/requiring-mfa-on-popular-gems.html
- https://guides.rubygems.org/mfa-requirement-opt-in/

Opt-in for MFA requirement explicitly on 2.4

---

README.md

This commit updates the README to reflect the Ruby versions that are known to work with version 2.x of the library. Specifically, it documents that version 2.x works on Ruby 3.x.
Ref: 0001864cfe0a1e76879179dfa1ba7b9e60d5a991

Update README with Ruby version compatibility

---

Gemfile

Pin `jar-dependencies` to `0.4.1`.
Ref: jruby/jruby#7262
Close #626

Fix JRuby CI tests

---

lib/zip/entry.rb

Without this, we see the following failure:
```
$ ruby -e'require "zip/entry"'
/usr/lib/ruby/gems/3.2.0/gems/rubyzip-3.0.0/lib/zip/entry.rb:13:in `<class:Entry>': uninitialized constant Zip::COMPRESSION_METHOD_STORE (NameError)
STORED   = ::Zip::COMPRESSION_METHOD_STORE
^^^^^^^^^^^^^^^^^^^^^^^^^^
from /usr/lib/ruby/gems/3.2.0/gems/rubyzip-3.0.0/lib/zip/entry.rb:9:in `<module:Zip>'
from /usr/lib/ruby/gems/3.2.0/gems/rubyzip-3.0.0/lib/zip/entry.rb:7:in `<top (required)>'
from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:40:in `require'
from -e:1:in `<main>' …
```

entry: fix direct `require` by requiring `constants`

---

lib/zip/crypto/aes_encryption.rb
lib/zip/crypto/decrypted_io.rb
lib/zip/crypto/null_encryption.rb
lib/zip/crypto/traditional_encryption.rb
lib/zip/input_stream.rb
test/crypto/null_encryption_test.rb

The key change here is to only use the decryption classes, and `DecryptedIo` when we're actually needed to decrypt something.
Some other simplifications are also included.

Improve the IO pipeline when decompressing.
